# Generated by Django 5.2.7 on 2025-10-28 08:39

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capital', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('currency_code', models.CharField(max_length=5)),
                ('estimated_gdp', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('flag_url', models.URLField(blank=True, max_length=255, null=True)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
